apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: csh37yhu3-nodejs
  janus-idp.io/tekton: csh37yhu3-nodejs
  backstage.io/kubernetes-id: csh37yhu3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: csh37yhu3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
